[tox]
envlist = py{310,312,314}-torch{210,213}
isolated_build = true 
skip_missing_interpreters = true

[testenv]
passenv = *

deps =
    pytest
    expecttest
    numpy
    torch210: torch==2.10.0
    torch213: torch==2.13.0
commands =
    pytest tests/