[tox]
envlist = py{310,312,314}-torch{20,26,213}
isolated_build = True 

[testenv]
deps =
    pytest
    expecttest
    numpy
    torch20: torch==2.0.0
    torch26: torch==2.6.0
    torch213: torch==2.13.0
commands =
    pytest tests/