[tox]
envlist = py{310,312,314}-torch{210,213}
isolated_build = true 
skip_missing_interpreters = true

[testenv]
passenv =
    VULKAN_SDK
    VK_SDK_PATH
    SKBUILD_CMAKE_GENERATOR
    MVK_CONFIG_LOG_LEVEL
    VK_LOADER_DEBUG
    PIP_EXTRA_INDEX_URL

[testenv]
deps =
    pytest
    expecttest
    numpy
    torch210: torch==2.10.0
    torch213: torch==2.13.0
commands =
    pytest tests/