import os

SHADER_DIR = 'src/shaders'
OUT_DIR = 'build/shaders'
SHADER_NAME = 'binaryop.slang'
MAX_DIMS = 4

DTYPES = [
    {'dtype' : 'int64_t',    'vecSize' : 2, 'wgSize' : 64,  'floating': False},
    {'dtype' : 'uint64_t',   'vecSize' : 2, 'wgSize' : 64,  'floating': False},
    {'dtype' : 'float64_t',  'vecSize' : 2, 'wgSize' : 64,  'floating': True},
    {'dtype' : 'int32_t',    'vecSize' : 4, 'wgSize' : 64,  'floating': False},
    {'dtype' : 'uint32_t',   'vecSize' : 4, 'wgSize' : 64,  'floating': False},
    {'dtype' : 'float32_t',  'vecSize' : 4, 'wgSize' : 64,  'floating': True},
    {'dtype' : 'int16_t',    'vecSize' : 4, 'wgSize' : 128, 'floating': False},
    {'dtype' : 'uint16_t',   'vecSize' : 4, 'wgSize' : 128, 'floating': False},
    {'dtype' : 'float16_t',  'vecSize' : 4, 'wgSize' : 128, 'floating': True},
    {'dtype' : 'int8_t',     'vecSize' : 4, 'wgSize' : 256, 'floating': False},
    {'dtype' : 'uint8_t',    'vecSize' : 4, 'wgSize' : 256, 'floating': False}
]

OPERATIONS = [
    {"name" : '0', 'struct' : 'AddOp', 'dtypes' : [dtype['dtype'] for dtype in DTYPES]},
    {"name" : '1', 'struct' : 'SubOp', 'dtypes' : [dtype['dtype'] for dtype in DTYPES]},
    {"name" : '2', 'struct' : 'RSubOp', 'dtypes' : [dtype['dtype'] for dtype in DTYPES]},
    {"name" : '3', 'struct' : 'MulOp', 'dtypes' : [dtype['dtype'] for dtype in DTYPES]},
    {"name" : '4', 'struct' : 'DivOp', 'dtypes' : [dtype['dtype'] for dtype in DTYPES]},
    {"name" : '5', 'struct' : 'MaxOp', 'dtypes' : [dtype['dtype'] for dtype in DTYPES]},
    {"name" : '6', 'struct' : 'MinOp', 'dtypes' : [dtype['dtype'] for dtype in DTYPES]},
    {"name" : '7', 'struct' : 'PowOp', 'dtypes' : [dtype['dtype'] for dtype in DTYPES]},
    {"name" : '8', 'struct' : 'RPowOp', 'dtypes' : [dtype['dtype'] for dtype in DTYPES]},
    {"name" : '9', 'struct' : 'Atan2Op', 'dtypes' : ['float64_t', 'float32_t', 'float16_t']},
]

def get_safe_cast(dtype):
    CAST = {
        'uint8_t' : '(uint8_t)(int8_t)',
        'uint16_t' : '(uint16_t)(int16_t)',
        'uint32_t' : '(uint32_t)(int32_t)',
        'uint64_t' : '(uint64_t)(int64_t)'
    }
    return CAST.get(dtype, f'({dtype})')

def generate_entrypoints():
    """Generates entry point shaders for each binary operation and data type combination."""
    base_shader = os.path.join(SHADER_DIR, SHADER_NAME)
    
    if not os.path.exists(base_shader):
        print(f"Skipping compilation phase: Base shader {base_shader} not found.")
        return
    
    out_shader = os.path.join(OUT_DIR, SHADER_NAME)
    os.makedirs(OUT_DIR, exist_ok=True)

    for dt in DTYPES:
        
        entrypoint_shader = out_shader.replace('.slang', f'_{dt["dtype"]}_entrypoint.slang')
        with open(entrypoint_shader, 'w') as f:
            f.write('// --- AUTO-GENERATED BY generate_binaryop_entrypoints.py --- //\n')
            f.write('// Do not edit manually!\n\n')
            f.write(f'#include "{SHADER_NAME}"\n\n')

            hlsl_type = dt['dtype']
            vec_size = dt['vecSize']

            f.write(f'DEFINE_EXT_POW_ATAN2_FOR_{"FLOAT" if dt["floating"] else "INT"}_TYPE({hlsl_type})\n\n')
            f.write(f'[[vk::binding(0, 0)]] StructuredBuffer<vector<{hlsl_type}, {vec_size}>> tensor_a_contig;\n')
            f.write(f'[[vk::binding(1, 0)]] StructuredBuffer<vector<{hlsl_type}, {vec_size}>> tensor_b_contig;\n')
            f.write(f'[[vk::binding(2, 0)]] RWStructuredBuffer<vector<{hlsl_type}, {vec_size}>> tensor_out_contig;\n\n')

            f.write(f'[[vk::binding(0, 0)]] StructuredBuffer<{hlsl_type}> tensor_a_noncontig;\n')
            f.write(f'[[vk::binding(1, 0)]] StructuredBuffer<{hlsl_type}> tensor_b_noncontig;\n')
            f.write(f'[[vk::binding(2, 0)]] RWStructuredBuffer<{hlsl_type}> tensor_out_noncontig;\n\n')

            wg_size = dt['wgSize']
            f.write(f'[shader("compute")]\n')
            f.write(f'[numthreads({wg_size}, 1, 1)]\n')
            f.write('void main(uint3 gi: SV_DispatchThreadID) {\n')

            for is_contig in [True, False]:
                for op in OPERATIONS:

                    if dt['dtype'] not in op['dtypes']:
                        continue

                    if is_contig:
                        f.write(f'   if (IS_CONTIG && OP_TYPE == {op["name"]}) baseBinaryKernel<{dt["dtype"]}, {dt["vecSize"]}, {op["struct"]}<vector<{dt["dtype"]}, {dt["vecSize"]}>>>(gi, tensor_a_contig, tensor_b_contig, tensor_out_contig, {get_safe_cast(dt["dtype"])}pcs.alpha, {get_safe_cast(dt["dtype"])}pcs.scalar_value);\n')
                        continue

                    for ndim in range(MAX_DIMS+1):
                        f.write(f'   if (!IS_CONTIG && OP_TYPE == {op["name"]} && NDIM == {ndim}) baseBinaryKernel<{dt["dtype"]}, {ndim}, {op["struct"]}<{dt["dtype"]}>>(gi, tensor_a_noncontig, tensor_b_noncontig, tensor_out_noncontig, {get_safe_cast(dt["dtype"])}pcs.alpha, {get_safe_cast(dt["dtype"])}pcs.scalar_value);\n')

            f.write('}')

            
if __name__ == "__main__":
    generate_entrypoints()