import os

SHADER_DIR = 'src/shaders'
OUT_DIR = 'build/shaders'
SHADER_NAME = 'copy.slang'
MAX_DIMS = 4

BYTE_SIZE_MAP = [
    {'dtype': 'uint64_t', 'wgSize' : 64},
    {'dtype': 'uint32_t', 'wgSize' : 64},
    {'dtype': 'uint16_t', 'wgSize' : 128},
    {'dtype': 'uint8_t',  'wgSize' : 256}   
]

def generate_entrypoints():
    """Generates entry point shaders for each binary operation and data type combination."""
    base_shader = os.path.join(SHADER_DIR, SHADER_NAME)
    
    if not os.path.exists(base_shader):
        print(f"Skipping compilation phase: Base shader {base_shader} not found.")
        return
    
    out_shader = os.path.join(OUT_DIR, SHADER_NAME)
    os.makedirs(OUT_DIR, exist_ok=True)

    for dt in BYTE_SIZE_MAP:

        entrypoint_shader = out_shader.replace('.slang', f'_{dt["dtype"]}_entrypoint.slang')
        with open(entrypoint_shader, 'w') as f:
            f.write('// --- AUTO-GENERATED BY scripts/shaders/copy.py --- //\n')
            f.write('// Do not edit manually!\n\n')
            f.write(f'#include "{SHADER_NAME}"\n\n')

            hlsl_type = dt['dtype']

            f.write(f'[[vk::binding(0, 0)]] StructuredBuffer<{hlsl_type}> tensor_in;\n')
            f.write(f'[[vk::binding(1, 0)]] RWStructuredBuffer<{hlsl_type}> tensor_out;\n\n')

            wg_size = dt['wgSize']
            f.write(f'[shader("compute")]\n')
            f.write(f'[numthreads({wg_size}, 1, 1)]\n')
            f.write('void main(uint3 gi: SV_DispatchThreadID) {\n')

            for ndim in range(MAX_DIMS+1):
                f.write(f'   if (NDIM == {ndim}) copyKernel<{dt['dtype']}, {ndim}>(gi, tensor_in, tensor_out);\n')
            
            f.write('}')

if __name__ == '__main__':
    generate_entrypoints()