import os
from jinja2 import Environment, FileSystemLoader
import config

SHADER_DIR = 'src/shaders'
OUT_DIR = 'build/shaders'

UTILS = {'MAX_DIMS' : 4}

def calculate_vecsize(bytes: int) -> int:
    return int(min(16/bytes, 4)) # slang has max vec size of 4

def generate_cast_entrypoints():

    os.makedirs(OUT_DIR, exist_ok=True)
    env = Environment(loader=FileSystemLoader(SHADER_DIR))

    for shader in config.SHADERS:
        template = env.get_template(shader['name'])
        for dtype in shader['dtypes']:
            filehead = shader['name'].split('.')[0]
            dtype_names = [x['name'] for x in dtype]
            filename = os.path.join(OUT_DIR, f'{filehead}_{"_".join(dtype_names)}_entrypoint.slang')
            render_kwargs = {f"d{i+1}": dt['dtype'] for i, dt in enumerate(dtype)}
            render_kwargs |= {f"v{i+1}": calculate_vecsize(dt['bytes']) for i, dt in enumerate(dtype)}

            spv_code = template.render(
                render_kwargs | UTILS | shader['kwargs']
            )

            with open(filename, 'w') as f:
                f.write('// --- AUTO-GENERATED BY scripts/build_shaders.py --- //\n')
                f.write('// Do not edit manually!\n\n')
                f.write(spv_code)

        print(f'Generated code for {shader['name']}!')

if __name__ == "__main__":
    generate_cast_entrypoints()