"""
Build script for generating Vulkan shader code and a corresponding C++ registry for dispatch.

This script performs the following steps:
1. Reads .comp.j2 shader templates from the specified source directory.
2. For each shader template, renders it with different datatype combinations as specified in scripts/config.py.
3. Writes the rendered shader code to .comp files in the specified output directory.
4. Extracts metadata about the generated shaders (e.g., which datatypes were generated for each shader) and generates a C++ header file containing:
   - Inline functions that map shader-relevant parameters (e.g., input dtypes) to the appropriate shader ID for dispatch at runtime.
"""

import os
from jinja2 import Environment, FileSystemLoader
import argparse
from pathlib import Path
import config
import itertools

UTILS = {'MAX_DIMS' : 4}
ATEN_TYPE_MAP = { 
    'f64': ['c10::ScalarType::Double'], 
    'f32': ['c10::ScalarType::Float'], 
    'f16': ['c10::ScalarType::Half'],
    'i64': ['c10::ScalarType::Long'],   
    'i32': ['c10::ScalarType::Int'],   
    'i16': ['c10::ScalarType::Short'], 
    'i8':  ['c10::ScalarType::Char'],
    'u64': ['c10::ScalarType::UInt64'], 
    'u32': ['c10::ScalarType::UInt32'],
    'u16': ['c10::ScalarType::UInt16'],
    'u8':  ['c10::ScalarType::Byte', 
            'c10::ScalarType::Bool']
}

def calculate_vecsize(bytes: int) -> int:
    """ 
    Generates a vector size for a given datatype based on its byte size.
    This determines how many elements of a given type can be packed into a 128-bit vector. 

    Inputs:
    - bytes: The byte size of the datatype (e.g., 4 for f32

    Outputs:
    - An integer vector size (1, 2, 4, or 8)
    """
    return int(min(16/bytes, 4))

def generate_shaders(src: Path, out: Path) -> dict:
    """
    Injects datatype, utils and shader-specific kwargs into the .comp.j2 templates, 
    renders them to .comp files, and extracts metadata for registry generation.

    Inputs:
    - src: Directory containing .comp.j2 shader templates
    - out: Directory to output rendered .comp shader files

    Outputs:
    - registry_data: A dictionary mapping shader base names to lists of generated datatype combinations.
    """
    os.makedirs(out, exist_ok=True)
    env = Environment(loader=FileSystemLoader(src))

    registry_data = {}

    for shader in config.SHADERS:
        template = env.get_template(shader['name'])
        filehead = shader['name'].split('.')[0]
        
        if filehead not in registry_data:
            registry_data[filehead] = []

        for dtype in shader['dtypes']:
            dtype_names = [x['name'] for x in dtype]
            filename = os.path.join(out, f'{filehead}_{"_".join(dtype_names)}_entrypoint.slang')
            
            render_kwargs = {f"d{i+1}": dt['dtype'] for i, dt in enumerate(dtype)}
            render_kwargs |= {f"v{i+1}": calculate_vecsize(dt['bytes']) for i, dt in enumerate(dtype)}
            render_kwargs |= {f"b{i+1}" : dt['bytes'] for i, dt in enumerate(dtype)}
            spv_code = template.render(render_kwargs | UTILS | shader['kwargs'])

            with open(filename, 'w') as f:
                f.write('// --- AUTO-GENERATED BY scripts/build_shaders.py --- //\n')
                f.write('// Do not edit manually!\n\n')
                f.write(spv_code)
            
            registry_data[filehead].append(dtype_names)

    return registry_data

def generate_cpp_registry(registry_data: dict, out: Path) -> None:
    """
    Generates a C++ header file containing:
    - An enum class of shader IDs corresponding to each generated shader.
    - Inline functions that map shader-relevant parameters (e.g., input dtypes) to
        the appropriate shader ID for dispatch at runtime.

    Inputs:
    - registry_data: A dictionary mapping shader base names to lists of generated datatype combinations.
    - out: Output path for the generated C++ header file.

    Outputs:
    - A C++ header file at the specified output path.
    """

    cpp_code = []
    cpp_code.append("// --- AUTO-GENERATED BY scripts/build_shaders.py --- //")
    cpp_code.append("// Do not edit manually!\n")
    cpp_code.append("#include <c10/core/ScalarType.h>")
    cpp_code.append("#include \"shader_registry.h\"\n")
    cpp_code.append("namespace torchvulkan {\n")

    for op_name, dtype_lists in registry_data.items():
        
        cpp_code.append(f"inline torchvulkan::ShaderID get_shader_id_{op_name}({', '.join([f'c10::ScalarType d{i}' for i in range(len(dtype_lists[0]))])}) {{")

        if dtype_lists[0][0].isdigit():
            cpp_code.append("size_t bytes = c10::elementSize(d0);")
            cpp_code.append(f"switch (bytes) {{")
            cpp_code.extend(f"case ({dtype[0]}):\n return torchvulkan::ShaderID::{op_name.upper()}_{'_'.join(dtype).upper()}_ENTRYPOINT;" for dtype in dtype_lists)

        elif len(dtype_lists[0]) > 1 and len(dtype_lists[0]) <= 4:
            key_parts = [f"(static_cast<uint64_t>(d{i}) << {i * 16})" for i in range(len(dtype_lists[0]))]
            cpp_code.append(f"uint64_t key = {' | '.join(key_parts)};\n")
            cpp_code.append("switch (key) {")

            for dtype in dtype_lists:
                
                if any(dt not in ATEN_TYPE_MAP for dt in dtype): 
                    continue
                
                dtype_pairs = list(itertools.product(*[ATEN_TYPE_MAP.get(dtype[i], []) for i in range(len(dtype))]))    
                for pair in dtype_pairs:
                    case_parts = [f"(static_cast<uint64_t>({x}) << {i * 16})" for i, x in enumerate(pair)]
                    case_expr = " | ".join(case_parts)
                    shader_id = f"{op_name.upper()}_{'_'.join(dtype).upper()}_ENTRYPOINT"
                    cpp_code.append(f"case ({case_expr}):")

                cpp_code.append(f" return torchvulkan::ShaderID::{shader_id};")
                
        elif len(dtype_lists[0]) == 1:
            cpp_code.append(f"switch ({', '.join([f'd{i}' for i in range(len(dtype_lists[0]))])}) {{")
            for dt in dtype_lists:
                dt = dt[0]
                cpp_code.extend([f"case ({type}):" for type in ATEN_TYPE_MAP.get(dt, "")])
                cpp_code.append(f" return torchvulkan::ShaderID::{op_name.upper()}_{dt.upper()}_ENTRYPOINT;")

        cpp_code.append("default:")
        cpp_code.append("TORCH_CHECK(false, \"Unsupported dtype combination for shader: " + op_name + "\");")
        cpp_code.append("}")
        cpp_code.append("}\n")

    cpp_code.append("} // namespace torchvulkan\n")

    with open(out, 'w') as f:
        f.write('\n'.join(cpp_code))
    print(f"Generated C++ shader registry ({out})!")

def main(args):
    registry_data = generate_shaders(args.src, args.out.parent)
    generate_cpp_registry(registry_data, args.out)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate lookup functions for all shaders given their generated datatypes.")
    parser.add_argument("--src", type=Path, default=Path("src/shaders"), help="Directory containing .comp source files")
    parser.add_argument("--out", type=Path, default=Path("build/shaders/shader_lookup.h"), help="Output header file path")
    args = parser.parse_args()

    main(args)