"""
Turns scripts/config.py into build instructions. Runs at CMake configure time
and writes:

  build/shaders/variants.cmake   one torchvulkan_add_shader(...) per variant,
                                 which src/shaders/CMakeLists.txt turns into a
                                 slangc -entry ... -specialize ... command
  build/shaders/variants.json    which ShaderKey each compiled variant serves,
                                 read by pack_shaders.py
  src/shaders/shader_kernels.h   enum class Kernel, the host's name for a kernel
"""

import argparse
import itertools
import json
from pathlib import Path

import config

HEADER = ('// --- AUTO-GENERATED BY scripts/build_shaders.py --- //\n'
          '// Do not edit manually - see scripts/config.py.\n\n')


def value_args(entry, nbytes):
    """The integer generic arguments that follow the type arguments."""
    derived = [str(config.VALUE_ARGS[name](nbytes)) for name in entry.value_args]
    return derived + [str(c) for c in entry.constants]


def kernel_variants(kernel, src):
    """
    Yields (variant name, source file, entry function, specialisation args,
    aten dtypes per type argument) for every variant of a kernel.
    """
    module = src / kernel.module

    for entry in kernel.entries:
        if entry.pairwise:
            for s, d in itertools.product(entry.dtypes, repeat=2):
                args = [s.slang, d.slang] + value_args(entry, max(s.bytes, d.bytes))
                yield f'{kernel.name}_{s.name}_{d.name}', module, entry.function, args, [s.aten, d.aten]
            continue

        for d in entry.dtypes:
            args = [d.slang] + value_args(entry, d.bytes)
            yield f'{kernel.name}_{d.name}', module, entry.function, args, [d.aten]


def write_if_changed(path, text):
    """Leaves the file untouched when nothing changed, so its dependents do not rebuild."""
    if path.exists() and path.read_text() == text:
        return
    path.write_text(text)


def cmake_quote(path):
    return '"' + str(path).replace('\\', '/') + '"'


def main(args):
    args.src = args.src.resolve()
    args.out = args.out.resolve()
    args.out.mkdir(parents=True, exist_ok=True)

    kernel_names = []
    cmake = [HEADER.replace('//', '#').rstrip('\n') + '\n']
    variants = []

    for kernel in config.KERNELS:
        kernel_names.append(kernel.name)

        for name, source, function, spec_args, aten in kernel_variants(kernel, args.src):
            cmake.append('torchvulkan_add_shader(' + ' '.join([name, cmake_quote(source), function] + spec_args) + ')')
            variants.append({'name': name, 'kernel': kernel.name, 'aten': aten})

    write_if_changed(args.out / 'variants.cmake', '\n'.join(cmake) + '\n')
    write_if_changed(args.out / 'variants.json', json.dumps(variants, indent=1) + '\n')

    enum = [HEADER + '#pragma once\n#include <cstdint>\n\nnamespace torchvulkan {\n']
    enum.append('enum class Kernel : uint8_t {')
    enum.extend(f'    {name.upper()},' for name in kernel_names)
    enum.append('    COUNT\n};\n')
    enum.append('inline constexpr const char* KERNEL_NAMES[] = {')
    enum.extend(f'    "{name}",' for name in kernel_names)
    enum.append('};\n')
    enum.append('} // namespace torchvulkan\n')
    write_if_changed(args.kernels_header, '\n'.join(enum))

    print(f'Configured {len(variants)} shader variants across {len(kernel_names)} kernels.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Write the shader variant list for CMake and the packer.')
    parser.add_argument('--src', type=Path, default=Path('src/shaders'), help='Directory containing shader sources')
    parser.add_argument('--out', type=Path, default=Path('build/shaders'), help='Directory for generated build files')
    parser.add_argument('--kernels-header', type=Path, default=Path('src/shaders/shader_kernels.h'), help='Generated Kernel enum header')
    main(parser.parse_args())