"""
Embeds the compiled shaders in the binary: for each variant listed by
scripts/build_shaders.py, writes its SPIR-V as a uint32_t array plus one index
row per dtype it serves.

Output (src/shaders/shader_registry.h), included only by src/vulkan/shader.cpp:

    inline constexpr uint32_t spv_binary_f32[] = { 0x07230203, ... };

    inline constexpr ShaderBinary SHADER_BINARIES[] = {
        { "binary_f32", spv_binary_f32, sizeof(spv_binary_f32) },
    };

    inline constexpr ShaderIndexEntry SHADER_INDEX[] = {
        { Kernel::BINARY, c10::ScalarType::Float, c10::ScalarType::Undefined, 0 },
    };
"""

import argparse
import itertools
import json
import struct
from pathlib import Path


def spv_to_c_array(spv_file: Path, array_name: str) -> str:
    """Reads a .spv binary and formats it as a C++ uint32_t array definition."""
    binary_data = spv_file.read_bytes()

    # pad to a multiple of 4 bytes
    if len(binary_data) % 4 != 0:
        binary_data += b'\x00' * (4 - (len(binary_data) % 4))

    words = struct.unpack(f'<{len(binary_data) // 4}I', binary_data)
    body = ''.join(f'0x{word:08x}, ' for word in words)
    return f'inline constexpr uint32_t {array_name}[] = {{\n    {body}\n}};\n'


def index_rows(variant: dict, binary: int) -> list[str]:
    """
    One SHADER_INDEX row per aten dtype combination the variant serves - a u8
    variant serves both Byte and Bool, and a copy width serves every dtype of
    that size.
    """
    kernel = f'Kernel::{variant["kernel"].upper()}'
    rows = []

    for combo in itertools.product(*variant['aten']):
        dtype = f'c10::ScalarType::{combo[0]}'
        dtype2 = f'c10::ScalarType::{combo[1]}' if len(combo) > 1 else 'c10::ScalarType::Undefined'
        rows.append(f'    {{ {kernel}, {dtype}, {dtype2}, {binary} }}, // {variant["name"]}')

    return rows


def main(args):
    variants = json.loads(args.variants.read_text())

    arrays = []
    binaries = []
    index = []

    for binary, variant in enumerate(variants):
        array_name = f'spv_{variant["name"]}'
        arrays.append(spv_to_c_array(args.build / f'{variant["name"]}.spv', array_name))
        binaries.append(f'    {{ "{variant["name"]}", {array_name}, sizeof({array_name}) }},')
        index.extend(index_rows(variant, binary))

    header = [
        '// --- AUTO-GENERATED BY scripts/pack_shaders.py --- //',
        '// Do not edit manually!\n',
        '#pragma once',
        '#include <c10/core/ScalarType.h>',
        '#include <cstddef>',
        '#include <cstdint>',
        '#include "shader_kernels.h"\n',
        'namespace torchvulkan {\n',
    ]
    header.extend(arrays)

    header.append('struct ShaderBinary {')
    header.append('    const char* name;')
    header.append('    const uint32_t* code;')
    header.append('    size_t size;')
    header.append('};\n')
    header.append('inline constexpr ShaderBinary SHADER_BINARIES[] = {')
    header.extend(binaries)
    header.append('};\n')

    header.append('struct ShaderIndexEntry {')
    header.append('    Kernel kernel;')
    header.append('    c10::ScalarType dtype;')
    header.append('    c10::ScalarType dtype2;')
    header.append('    uint32_t binary;')
    header.append('};\n')
    header.append('inline constexpr ShaderIndexEntry SHADER_INDEX[] = {')
    header.extend(index)
    header.append('};\n')

    header.append('} // namespace torchvulkan\n')
    args.out.write_text('\n'.join(header))
    print(f'Packed {len(variants)} shaders into {args.out}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Pack compiled Vulkan shaders into a C++ header.')
    parser.add_argument('--build', type=Path, default=Path('build/shaders'), help='Directory containing compiled .spv files')
    parser.add_argument('--variants', type=Path, default=Path('build/shaders/variants.json'), help='Variant list written by build_shaders.py')
    parser.add_argument('--out', type=Path, default=Path('src/shaders/shader_registry.h'), help='Output header file path')
    main(parser.parse_args())
