import os
import re
import struct
import glob
import argparse
from pathlib import Path

def parse_comp_file(filepath: str) -> tuple[int, int]:
    """Extracts num_bindings and push_constant_size from a .comp file."""
    
    with open(filepath, 'r') as f:
        code = f.read()

    bindings = re.findall(r'layout\s*\(\s*binding\s*=\s*\d+\s*\)', code)
    num_bindings = len(bindings)

    pc_match = re.search(r'layout\s*\(\s*push_constant\s*\).*?\{([^}]+)\}', code, re.DOTALL)
    pc_size = 0
    if pc_match:
        struct_body = pc_match.group(1)
        num_types = len(re.findall(r'\b(uint|int|float)\b', struct_body))
        pc_size = num_types * 4

    return num_bindings, pc_size

def spv_to_c_array(spv_file: str, array_name: str) -> str:
    """Reads a .spv binary and converts it to a formatted C++ uint32_t array string."""
    
    with open(spv_file, 'rb') as f:
        binary_data = f.read()
    
    # pad to a multiple of 4 bytes
    if len(binary_data) % 4 != 0:
        binary_data += b'\x00' * (4 - (len(binary_data) % 4))
        
    words = struct.unpack(f'<{len(binary_data)//4}I', binary_data)
    
    line = "    "
    for word in words:
        line += f"0x{word:08x}, "
        
    return f"inline constexpr uint32_t {array_name}[] = {{\n" + line + "\n};\n"

def main(args):
    
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    spv_files = glob.glob(os.path.join(args.build, "*.spv"))
    
    if not spv_files:
        print(f"Warning: No .spv files found in {args.build}. Creating empty registry.")

    enum_entries = []
    array_definitions = []
    catalog_entries = []
    
    for spv_path in sorted(spv_files):

        filename = os.path.basename(spv_path)
        base_name = os.path.splitext(filename)[0]
        comp_path = os.path.join(args.src, f"{base_name}.comp")

        if not os.path.exists(comp_path):
            generic_base = base_name.split('_')[0] + '_' + base_name.split('_')[1] 
            comp_path = os.path.join(args.src, f"{generic_base}.comp")
            
        num_bindings, pc_size = parse_comp_file(comp_path)
        
        enum_name = base_name.upper()
        array_name = f"spv_{base_name}"
        
        enum_entries.append(f"    {enum_name},")
        array_definitions.append(spv_to_c_array(spv_path, array_name))
        
        catalog_entries.append(
            f"    {{ ShaderID::{enum_name}, {array_name}, sizeof({array_name}), {pc_size}, {num_bindings} }}, // {enum_name}"
        )
        
        print(f"Packed {base_name}: {num_bindings} bindings, {pc_size} bytes PC")

    header_content = f"""// --- AUTO-GENERATED BY pack_shaders.py --- //
// Do not edit manually!
#pragma once
#include <cstdint>
#include <cstddef>

namespace torchvulkan {{

enum class ShaderID {{
{chr(10).join(enum_entries)}
    SHADER_COUNT
}};

struct Shader {{
    ShaderID shaderId;
    const uint32_t* binaryCode;
    size_t binarySize;
    uint32_t pushConstantSize;
    uint32_t numBindings;
}};

{chr(10).join(array_definitions)}

inline constexpr Shader SHADER_CATALOG[] = {{
{chr(10).join(catalog_entries)}
}};

inline Shader getShader(ShaderID id) {{
    return SHADER_CATALOG[static_cast<uint32_t>(id)];
}}

}} // namespace torchvulkan"""

    with open(args.out, 'w') as f:
        f.write(header_content)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Pack compiled Vulkan shaders into a C++ header.")
    parser.add_argument("--src", type=Path, default=Path("src/shaders"), help="Directory containing .comp source files")
    parser.add_argument("--build", type=Path, default=Path("build/shaders"), help="Directory containing compiled .spv files")
    parser.add_argument("--out", type=Path, default=Path("src/shaders/shader_registry.h"), help="Output header file path")
    args = parser.parse_args()

    main(args)